name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Set version
        run: echo "version := \"${GITHUB_REF/refs\/tags\//}\"" > version.sbt
      - name: Test
        run: sbt +test
      - name: Publish
        run: sbt +publish
